{% set name = "esbmtk" %}
{% set version = "0.14.1.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esbmtk-{{ version }}.tar.gz
  sha256: 81625dfc7c305e2e1dcebc3b585678c48d334f2850eae9565c61f6577ed0d455

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - pandas
    - matplotlib-base
    - numpy
    - numba
    - pint
    - psutil
    - pyco2sys >=1.8.3.3
    - scipy
    - cachetools

test:
  imports:
    - esbmtk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uliw/esbmtk
  summary: The Earth Science Box Modeling Toolkit
  dev_url: https://github.com/uliw/esbmtk
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - uliw
