{% set name = "esbmtk" %}
{% set version = "0.14.1.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esbmtk-{{ version }}.tar.gz
  sha256: adde9cf8ed09592d96405efda258be88aa4136b0c358b7a1be8e36f6e82d03a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
[[id:273791a7-a003-4d86-a813-cf6a0b78ee2c][conda forge feedstocks]]
requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - pandas
    - matplotlib-base
    - numpy
    - numba
    - pint
    - psutil
    - pyco2sys >=1.8.3.3
    - scipy
    - cachetools

test:
  imports:
    - esbmtk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uliw/esbmtk
  summary: The Earth Science Box Modeling Toolkit
  dev_url: https://github.com/uliw/esbmtk
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - uliw
