{% set name = "esbmtk" %}
{% set version = "0.12.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esbmtk-{{ version }}.tar.gz
  sha256: 0a58c91c5147ddc444f203cb8bc7ce870202130d383c89c9b8f9645f09a32699

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >=3.10
    - importlib-metadata
    - pandas
    - matplotlib-base
    - numpy
    - numba
    - pint
    - psutil
    - pyco2sys
    - scipy
    - typing

test:
  imports:
    - esbmtk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uliw/esbmtk
  summary: The Earth Science Box Modeling Toolkit
  dev_url: https://github.com/uliw/esbmtk
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - uliw
